"""init_user

Revision ID: 18246bd35219
Revises:
Create Date: 2025-12-26 14:11:36.614919

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18246bd35219"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("is_phone_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("totp_secret", sa.String(length=32), nullable=True),
        sa.Column("is_2fa_enabled", sa.Boolean(), nullable=False),
        sa.Column("backup_codes", sa.Text(), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("last_login_ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_phone"), ["phone"], unique=True)

    op.create_table(
        "auth_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("GOOGLE", "GITHUB", name="authproviderenum"),
            nullable=False,
        ),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_data", sa.JSON(), nullable=True),
        sa.Column("linked_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_provider_user_id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_user_provider"),
    )
    with op.batch_alter_table("auth_providers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_providers_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_auth_providers_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "otp_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("purpose", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("otp_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_otp_codes_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_otp_codes_phone"), ["phone"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_otp_codes_purpose"), ["purpose"], unique=False
        )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token"), ["token"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("otp_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_otp_codes_purpose"))
        batch_op.drop_index(batch_op.f("ix_otp_codes_phone"))
        batch_op.drop_index(batch_op.f("ix_otp_codes_email"))

    op.drop_table("otp_codes")
    with op.batch_alter_table("auth_providers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_providers_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_providers_provider"))

    op.drop_table("auth_providers")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_phone"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
